create table if not exists public.repair_rates (
    id bigint generated by default as identity primary key,
    date date not null,
    production_type text not null default 'Coil',
    project_no text not null,
    dimensions text not null,
    qty double precision not null,
    project_total_pipe_length double precision not null,
    repaired_pipes_total_length double precision not null,
    repaired_spiral_length double precision not null,
    total_repair_amount double precision not null,
    total_repair_amount_incl_skelp double precision not null,
    project_status text not null,
    repair_ratio double precision not null check (repair_ratio >= 0 and repair_ratio <= 1),
    repair_ratio_incl_skelp double precision not null check (repair_ratio_incl_skelp >= 0 and repair_ratio_incl_skelp <= 1),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_repair_rates_day_project_dimension unique (date, project_no, dimensions),
    constraint chk_repair_ratio_skelp check (repair_ratio_incl_skelp >= repair_ratio),
    constraint chk_repair_amount_skelp check (total_repair_amount_incl_skelp >= total_repair_amount)
);

create table if not exists public.historical_baselines (
    id bigint generated by default as identity primary key,
    project_no text not null,
    dimensions text not null default 'Historical Baseline',
    repaired_spiral_length double precision not null,
    total_repair_amount double precision not null,
    total_repair_amount_incl_skelp double precision not null,
    project_status text not null default 'Completed',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_historical_baselines_project_dimension unique (project_no, dimensions),
    constraint chk_historical_baseline_repair_amount_skelp check (total_repair_amount_incl_skelp >= total_repair_amount)
);

create index if not exists idx_repair_rates_date on public.repair_rates (date);
create index if not exists idx_repair_rates_production_type on public.repair_rates (production_type);
create index if not exists idx_repair_rates_project_no on public.repair_rates (project_no);
create index if not exists idx_repair_rates_dimensions on public.repair_rates (dimensions);
create index if not exists idx_historical_baselines_project_no on public.historical_baselines (project_no);

create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_repair_rates_updated_at on public.repair_rates;
create trigger trg_repair_rates_updated_at
before update on public.repair_rates
for each row execute function public.set_updated_at();

alter table public.repair_rates enable row level security;
alter table public.historical_baselines enable row level security;

grant usage on schema public to anon;
grant select, insert, update on public.repair_rates to anon;
grant select, insert, update on public.historical_baselines to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "repair_rates_select_anon" on public.repair_rates;
create policy "repair_rates_select_anon"
on public.repair_rates
for select
to anon
using (true);

drop policy if exists "repair_rates_insert_anon" on public.repair_rates;
create policy "repair_rates_insert_anon"
on public.repair_rates
for insert
to anon
with check (true);

drop policy if exists "repair_rates_update_anon" on public.repair_rates;
create policy "repair_rates_update_anon"
on public.repair_rates
for update
to anon
using (true)
with check (true);

drop policy if exists "historical_baselines_select_anon" on public.historical_baselines;
create policy "historical_baselines_select_anon"
on public.historical_baselines
for select
to anon
using (true);

drop policy if exists "historical_baselines_insert_anon" on public.historical_baselines;
create policy "historical_baselines_insert_anon"
on public.historical_baselines
for insert
to anon
with check (true);

drop policy if exists "historical_baselines_update_anon" on public.historical_baselines;
create policy "historical_baselines_update_anon"
on public.historical_baselines
for update
to anon
using (true)
with check (true);
