create table if not exists public.historical_baselines (
    id bigint generated by default as identity primary key,
    project_no text not null,
    dimensions text not null default 'Historical Baseline',
    repaired_spiral_length double precision not null,
    total_repair_amount double precision not null,
    total_repair_amount_incl_skelp double precision not null,
    project_status text not null default 'Completed',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_historical_baselines_project_dimension unique (project_no, dimensions),
    constraint chk_historical_baseline_repair_amount_skelp check (total_repair_amount_incl_skelp >= total_repair_amount)
);

create index if not exists idx_historical_baselines_project_no on public.historical_baselines (project_no);

alter table public.historical_baselines enable row level security;

grant usage on schema public to anon;
grant select, insert, update on public.historical_baselines to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "historical_baselines_select_anon" on public.historical_baselines;
create policy "historical_baselines_select_anon"
on public.historical_baselines
for select
to anon
using (true);

drop policy if exists "historical_baselines_insert_anon" on public.historical_baselines;
create policy "historical_baselines_insert_anon"
on public.historical_baselines
for insert
to anon
with check (true);

drop policy if exists "historical_baselines_update_anon" on public.historical_baselines;
create policy "historical_baselines_update_anon"
on public.historical_baselines
for update
to anon
using (true)
with check (true);
