create table if not exists public.project_group_configs (
    id bigint generated by default as identity primary key,
    project_sheet text not null,
    project_no text not null,
    dimensions text not null,
    pipe_groups text not null default '',
    machine_groups text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_project_group_configs_project unique (project_sheet, project_no, dimensions)
);

create index if not exists idx_project_group_configs_project_sheet
on public.project_group_configs (project_sheet);

create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

alter table public.project_group_configs enable row level security;

grant usage on schema public to anon;
grant select, insert, update on public.project_group_configs to anon;
grant usage, select on all sequences in schema public to anon;

drop trigger if exists trg_project_group_configs_updated_at on public.project_group_configs;
create trigger trg_project_group_configs_updated_at
before update on public.project_group_configs
for each row execute function public.set_updated_at();

drop policy if exists "project_group_configs_select_anon" on public.project_group_configs;
create policy "project_group_configs_select_anon"
on public.project_group_configs
for select
to anon
using (true);

drop policy if exists "project_group_configs_insert_anon" on public.project_group_configs;
create policy "project_group_configs_insert_anon"
on public.project_group_configs
for insert
to anon
with check (true);

drop policy if exists "project_group_configs_update_anon" on public.project_group_configs;
create policy "project_group_configs_update_anon"
on public.project_group_configs
for update
to anon
using (true)
with check (true);
